# Generated by Django 4.1.4 on 2022-12-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expensecategory_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense categories'},
        ),
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
